name: create release
on: 
  workflow_dispatch:
    branches: 
      - main
  push:
    branch:
      - main

jobs:
  build-release: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: get tag
        id: tagForRelease
        run: |
          echo ::set-output name=tag::${tag}
      - name: create release
        uses:  google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          release-as: ${{ steps.tagForRelease.outputs.tag }}
          # tag: ${{ steps.tagForRelease.outputs.tag }}

