name: create release
on: 
  workflow_dispatch:
    branches: 
      - main
      - dev
  push:
    branches:
      - main
jobs:
  build-release: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: get tag
        id: tagForRelease
        run: |
          tag=$(grep -o 'releases/[^ ,\/]\+/' Dockerfile | awk -F '/' '{ print $2 }')
          echo ::set-output name=tag::${tag}
      - name: create release
        uses:  google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          release-as: ${{ steps.tagForRelease.outputs.tag }}
          # tag: ${{ steps.tagForRelease.outputs.tag }}
      - name: prepare deploy
        if: ${{ steps.release.outputs.release_created }}
        run:  |
          mkdir target
          cp *.* target/.
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        if: ${{ steps.release.outputs.release_created }}
        env:
          REPO: self
          BRANCH: dev-release/test-1
          FOLDER: target
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




